version: 1
formatters:
  unstamped:
    format: '%(name)-6s %(levelname)-8s %(message)s'
  stamped:
    format: '%(asctime)s %(name)-6s %(levelname)-8s : %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: unstamped
    level: WARNING
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: stamped
    level: INFO
    filename: '~/.kbmlocal/kbm.log'
    when: midnight
    backupCount: 7
    delay: True
loggers:
  KBM:
    level: DEBUG
    handlers: [console, file]
  root:
    level: DEBUG
    handlers: [console]
